apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-capstone-api
  labels:
    app: capstone-api
    release: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-api
      release: blue
  template:
    metadata:
      labels:
        app: capstone-api
        release: blue
    spec:
      containers:
      - name: capstone-api
        image: mcastellin/udacity-capstone-api:${tagid}
        ports:
        - containerPort: 80
